/*---------------------------------------------------------------------------------

    snesgame2 - Genesis Invaders (PVSnesLib)

    Move the SNES sprite with the D-pad, fire with A/B. Sega Genesis consoles
    drop in from the top of the screen; shoot one and it flashes then vanishes.
    Press Y to set off a screen-clearing bomb.

---------------------------------------------------------------------------------*/
#include <snes.h>

#include "sprites.inc"          // player: sprites_til/_tilend, sprites_pal/_palend
#include "enemy.inc"            // enemy:  enemy_til/_tilend,   enemy_pal/_palend
#include "bullet.inc"           // bullet: bullet_til/_tilend,  bullet_pal/_palend
#include "powerup.inc"          // bomb pickup: powerup_til/_tilend, powerup_pal/_palend
#include "tac2.inc"             // tough enemy: tac2_til/_tilend,   tac2_pal/_palend

#include "res/soundbank.h"      // soundbank module ids (generated by smconv)

// Font tiles + palette, linked from data.asm
extern char tilfont, palfont;

// Sound effect bank (generated by smconv into res/soundbank.asm)
extern char SOUNDBANK__;

// Gun-fire BRR sample (linked from data.asm). brrsamples holds the registered
// sound-table entry that spcSetSoundEntry fills in.
extern char gunshot_brr, gunshot_brrend;
brrsamples gunSound;

// --- Sound effects -------------------------------------------------------------
// The bank holds 5 sampled instruments (loaded as effects 0..4). We reuse them
// for game events, leaning on pitch/volume to give each its own character.
// spcEffect(pitch, sfxIndex, volpan): pitch 1=4kHz..8=32kHz, volpan = vol*16+pan.
#define SFX_TADA      0
#define SFX_STRINGS   1
#define SFX_PIANO     2
#define SFX_MARIMBA   3
#define SFX_COWBELL   4
#define NUM_SFX       5

#define PAN_CENTER    8

// Gun fire: a real noise-burst gunshot BRR sample (see tools/make_gunshot.js),
// not a pitched instrument -- spcPlaySound(0) replays the last-loaded sound.
#define sfxFire()     spcPlaySound(0)
// Enemy hit: a clean high marimba "ding" to confirm the kill.
#define sfxEnemyHit() spcEffect(8,  SFX_MARIMBA, 12 * 16 + PAN_CENTER)
// Tough enemy chipped but not killed: a duller, lower marimba "thunk".
#define sfxTankHit()  spcEffect(4,  SFX_MARIMBA, 10 * 16 + PAN_CENTER)
// Player collision: a low, hard metallic cowbell whack at max volume -- the
// percussive sample gives it a sharp attack (punch) and the low pitch makes it
// harsh rather than the softer piano thud it used to be.
#define sfxCollide()  spcEffect(2,  SFX_COWBELL, 15 * 16 + PAN_CENTER)
// Game over: deep, slow strings = mournful.
#define sfxGameOver() spcEffect(1,  SFX_STRINGS, 15 * 16 + PAN_CENTER)
// Bomb power-up collected: a bright, high "tada" flourish.
#define sfxPowerup()  spcEffect(8,  SFX_TADA, 14 * 16 + PAN_CENTER)

// --- Title-screen fanfare ------------------------------------------------------
// A short, hard-driving riff played on the percussive cowbell sample (sharp
// attack = punch) at full volume while the splash screen is up. spcEffect pitch
// indices map to playback rates of 4*index kHz, so the indices 4:6:8 sound that
// same frequency ratio -- root, fifth and octave. The riff leans on the low root
// (4) on the beat with high stabs (8) for an aggressive, galloping feel.
#define JINGLE_STEP_FRAMES 6                // frames each note is held (~10 notes/sec, driving)
const unsigned char jingleNotes[] = {
    8, 4, 8, 6,  4, 8, 6, 4    // fast, accented arpeggio -- punchy low root on every beat
};
#define JINGLE_LEN (sizeof(jingleNotes))

#define SCREEN_W      256
#define ENEMY_SIZE    21        // art is 2/3 of the 32x32 cell (rest transparent)
#define PLAYER_SIZE   21
#define BULLET_SIZE   8
#define MAX_ENEMIES   12        // hard cap: sizes the enemy arrays + reserved OAM slots
#define START_ENEMIES 3         // active enemies on screen at score 0
#define ENEMIES_PER_LEVEL 1000  // +1 active enemy per this many points; slow ramp to MAX_ENEMIES
                                // (SCORE_PER_KILL is 100, so ~10 kills per extra enemy)
#define NUM_BULLETS   4
#define NUM_STARS     24        // falling background starfield
#define BULLET_SPEED  4
#define FLASH_FRAMES  12        // how long a hit console blinks before it disappears
#define OFFSCREEN_Y   224       // park spot for hidden sprites. Must clear the 224-line
                                // screen (y >= 224) AND keep a 32-tall sprite from wrapping:
                                // SNES sprite Y is 8-bit, so y+31 must stay <= 255 or the
                                // sprite's lower rows reappear at the top of the screen
                                // (the upper-left "ghost"). y = 224 is the only value that
                                // satisfies both for our 32x32 player/enemy sprites.
#define PLAYFIELD_TOP 24        // top 3 tile-rows (y 0..23) are the stats bar
#define SCORE_PER_KILL 100
#define TANK_SCORE    300       // a 3-hit TAC-2 joystick is worth triple a console
#define TANK_HEALTH   3         // hits to destroy the tough enemy
#define TANK_CHANCE   5         // ~1 in this many spawns is a tough enemy
#define HURT_FRAMES   8         // brief flicker after a non-lethal hit
// Enemy kinds (per-slot): a normal Genesis console, or the tough TAC-2 joystick.
#define ENEMY_NORMAL  0
#define ENEMY_TANK    1
#define START_LIVES   5
#define START_BOMBS   1
#define MAX_BOMBS     9         // inventory is shown as a single HUD digit
#define POWERUP_SIZE  16        // bomb-pickup hit-box. The bomb art is drawn at half
                                // size (16x16) in the top-left of its 32x32 sprite cell,
                                // so the catch box is the upper-left 16x16 of the cell.
#define POWERUP_SPEED 1         // pixels/frame the dropped bomb falls
#define PLAYER_FLASH_FRAMES 60  // ~1s of blink + invulnerability after a hit

// Each gfx4snes 32x32 sprite is a 64-tile (0x400-word) block; lay them end to end.
#define VRAM_PLAYER   0x0000
#define VRAM_ENEMY    0x0400
#define VRAM_BULLET   0x0800
#define VRAM_POWERUP  0x0C00    // free VRAM gap (0x0C00..0x0FFF), below the starfield
// The TAC-2 enemy block sits in the free 0x400-word gap between the starfield
// map (ends 0x1BFF) and BG0 gfx (0x2000) -- still inside the sprite name range.
#define VRAM_TANK     0x1C00
#define GFX_PLAYER    0x0000
#define GFX_ENEMY     0x0040    // VRAM_ENEMY   / 16
#define GFX_BULLET    0x0080    // VRAM_BULLET  / 16
#define GFX_POWERUP   0x00C0    // VRAM_POWERUP / 16
#define GFX_TANK      0x01C0    // VRAM_TANK    / 16

// Sprite palettes live at CGRAM 128, 16 entries apart.
#define PAL_ENEMY_CG   (128 + 1 * 16)
#define PAL_BULLET_CG  (128 + 2 * 16)
#define PAL_POWERUP_CG (128 + 3 * 16)
#define PAL_TANK_CG    (128 + 4 * 16)
#define PAL_TANK_SP    4        // sprite palette number for the TAC-2 (CGRAM 192..207)

// OAM sprite ids are the sprite index * 4.
#define OAM_PLAYER    0
#define OAM_ENEMY(i)  (((i) + 1) * 4)
#define OAM_BULLET(j) (((j) + 1 + MAX_ENEMIES) * 4)
#define OAM_POWERUP   ((1 + MAX_ENEMIES + NUM_BULLETS) * 4)

// --- Dark blue night-sky backdrop (CGRAM entry 0) ---
#define SKY_COLOR     RGB5(2, 4, 12)

// --- Scrolling starfield on BG2 (the 4-color/2bpp layer in mode 1) ---
// A static tilemap of single-pixel "stars" that we just scroll vertically each
// frame: one register write, no per-star sprite work and no scanline pressure.
// BG char base must be 0x1000-word aligned; map base 0x400-aligned. Both live in
// the free VRAM gap above the sprite tiles (0x0000..0x0BFF) and below BG0 (0x2000).
#define STAR_GFX_VRAM  0x1000   // tile gfx, char base (0x1000..0x11FF used)
#define STAR_MAP_VRAM  0x1800   // 32x32 map = 0x400 words (0x1800..0x1BFF)
#define NUM_STARS      32       // a sparse scatter of distinct stars over 256x256
#define STAR_PAL       4        // BG sub-palette -> CGRAM 16..19, clear of the font (0..15)
#define STAR_SCROLL_PX 1        // pixels the field drifts down per frame

// --- Enemy state ---
short enemyX[MAX_ENEMIES];
short enemyY[MAX_ENEMIES];      // logical y (pixels); negative = sliding in from the top
short enemySpeed[MAX_ENEMIES];           // descent speed in 1/256ths of a pixel per frame
unsigned char enemyFrac[MAX_ENEMIES];    // sub-pixel accumulator for slow movement
unsigned char enemyFlash[MAX_ENEMIES];   // >0 while playing the death/blink animation
unsigned char enemyHurt[MAX_ENEMIES];    // >0 = brief flicker after a non-lethal hit
unsigned char enemyType[MAX_ENEMIES];    // ENEMY_NORMAL (console) or ENEMY_TANK (joystick)
unsigned char enemyHealth[MAX_ENEMIES];  // hits remaining before destruction
unsigned char activeEnemies = START_ENEMIES;  // how many enemies are live right now;
                                              // grows with score up to MAX_ENEMIES
unsigned short nextEnemyScore = ENEMIES_PER_LEVEL;  // score at which the next enemy joins
                                                    // (a running threshold -- avoids a
                                                    // per-frame divide)

// --- Score ---
unsigned short score = 0;
unsigned short lastScore = 0xFFFF;       // force first HUD draw
char scoreStr[8];

// --- Player lives / state ---
unsigned char lives = START_LIVES;
unsigned char lastLives = 0xFF;          // force first HUD draw
unsigned char playerFlash = 0;           // >0 = recently hit: blinking + invulnerable
unsigned char gameOver = 0;
char livesStr[4];

// --- Bomb inventory ---
unsigned char bombs = START_BOMBS;
unsigned char lastBombs = 0xFF;          // force first HUD draw
char bombStr[4];

// --- Bullet state ---
short bulletX[NUM_BULLETS];
short bulletY[NUM_BULLETS];
unsigned char bulletActive[NUM_BULLETS];

// --- Bomb power-up drop ---
// At most one bomb pickup exists at a time: it falls straight down from a
// destroyed console, and catching it adds a bomb to the inventory.
short powerupX, powerupY;
unsigned char powerupActive = 0;
unsigned char killsSinceDrop = 0;        // kills counted toward the next drop
unsigned char dropThreshold  = 10;       // drop after ~this many kills (jittered)

// --- Falling starfield (BG2 layer, behind everything) ---
// Tile 0 is blank; tiles 1..NUM_STARS each carry exactly one star pixel, so every
// star is its own crisp point with no repeating tile pattern.
unsigned char  starTiles[(NUM_STARS + 1) * 16]; // 2bpp tile gfx, built at startup
unsigned short starMap[32 * 32];                // 32x32 tilemap, built at startup
unsigned short starScroll = 0;                  // current vertical scroll offset

// --- 16-bit xorshift PRNG ---
unsigned short rngState = 0xACE1;
unsigned short rnd(void)
{
    rngState ^= rngState << 7;
    rngState ^= rngState >> 9;
    rngState ^= rngState << 8;
    return rngState;
}

// Point an enemy's OAM slot at the right gfx + palette for its kind. The console
// and the TAC-2 joystick live in separate VRAM/palette slots, so this must run
// whenever a slot's type changes (i.e. on every spawn). Position is set per-frame
// by the draw loop, so park it off-screen here.
void setEnemyAppearance(unsigned char i)
{
    if (enemyType[i] == ENEMY_TANK)
        oamSet(OAM_ENEMY(i), 0, OFFSCREEN_Y, 2, 0, 0, GFX_TANK, PAL_TANK_SP);
    else
        oamSet(OAM_ENEMY(i), 0, OFFSCREEN_Y, 2, 0, 0, GFX_ENEMY, 1);
    oamSetEx(OAM_ENEMY(i), OBJ_LARGE, OBJ_SHOW);
}

// (Re)spawn an enemy above the top of the screen at a random column/speed.
// Roughly 1 in TANK_CHANCE is a tough TAC-2 joystick: 3 hits to kill, and it
// descends more slowly to offset the extra effort it takes to destroy.
void spawnEnemy(unsigned char i)
{
    short nx = (short)(rnd() & 0xFF);
    if (nx > SCREEN_W - ENEMY_SIZE) nx -= ENEMY_SIZE;   // keep fully on-screen (0..224)
    enemyX[i]     = nx;
    enemyY[i]     = -ENEMY_SIZE - (short)(rnd() & 0x7F); // staggered above the screen
    enemyFrac[i]  = 0;
    enemyFlash[i] = 0;
    enemyHurt[i]  = 0;

    if ((rnd() % TANK_CHANCE) == 0)
    {
        enemyType[i]   = ENEMY_TANK;
        enemyHealth[i] = TANK_HEALTH;
        enemySpeed[i]  = 60 + (rnd() & 0x1F);           // ~0.23..0.36 px/frame (heavier)
    }
    else
    {
        enemyType[i]   = ENEMY_NORMAL;
        enemyHealth[i] = 1;
        enemySpeed[i]  = 100 + (rnd() & 0x3F);          // ~0.39..0.64 px/frame
    }
    setEnemyAppearance(i);
}

// Build the starfield once. Each star gets its own tile holding a single pixel
// and is dropped into its own (empty) map cell, so the result is sparse, evenly
// spread, distinct points -- not a repeating, noisy texture. After this the
// layer is static data; we only ever change its scroll offset.
void buildStarfield(void)
{
    unsigned short i, cell;
    unsigned char  s, row, col, plane;

    for (i = 0; i < (NUM_STARS + 1) * 16; i++) starTiles[i] = 0;  // all tiles blank
    for (i = 0; i < 32 * 32; i++) starMap[i] = 0;                 // empty field

    for (s = 1; s <= NUM_STARS; s++)
    {
        do { cell = rnd() & 0x3FF; } while (starMap[cell] != 0);  // one star per cell
        row   = rnd() & 7;
        col   = rnd() & 7;
        // Mostly dim (color 2); roughly one in four is a bright (color 1) star.
        plane = ((rnd() & 3) == 0) ? 0 : 1;
        starTiles[s * 16 + row * 2 + plane] = 1 << (7 - col);
        starMap[cell] = (unsigned short)s | (STAR_PAL << 10);
    }
}

// Drop a bomb power-up at (sx, sy) -- where a console was just destroyed --
// unless one is already falling. Clamp into the playfield so it stays visible.
void spawnPowerup(short sx, short sy)
{
    if (powerupActive) return;
    if (sy < PLAYFIELD_TOP) sy = PLAYFIELD_TOP;
    powerupX = sx;
    powerupY = sy;
    powerupActive = 1;
}

// Destroy an enemy: start the death animation, score it, and maybe drop a bomb.
// A no-op if it's already dying. Tougher TAC-2 joysticks are worth more points.
void killEnemy(unsigned char i)
{
    if (enemyFlash[i] == 0)
    {
        enemyFlash[i] = FLASH_FRAMES;
        score += (enemyType[i] == ENEMY_TANK) ? TANK_SCORE : SCORE_PER_KILL;
        sfxEnemyHit();

        // Roughly every ~10 kills, drop a bomb power-up where this enemy died.
        if (++killsSinceDrop >= dropThreshold && !powerupActive)
        {
            spawnPowerup(enemyX[i], enemyY[i]);
            killsSinceDrop = 0;
            dropThreshold  = 8 + (rnd() % 5);    // 8..12 kills until the next one
        }
    }
}

// Apply one bullet's worth of damage to an enemy. A normal console dies in one
// hit; the tough TAC-2 joystick soaks up HURT hits (flickering each time) and
// only dies on the blow that drops its health to zero.
void damageEnemy(unsigned char i)
{
    if (enemyFlash[i] > 0) return;               // already dying
    if (enemyHealth[i] > 1)
    {
        enemyHealth[i]--;
        enemyHurt[i] = HURT_FRAMES;              // brief "chipped" flicker
        sfxTankHit();
        return;
    }
    killEnemy(i);
}

// Fire a bullet from the player's top-centre, if a slot is free.
void fireBullet(short px, short py)
{
    unsigned char j;
    for (j = 0; j < NUM_BULLETS; j++)
    {
        if (!bulletActive[j])
        {
            bulletActive[j] = 1;
            bulletX[j] = px + (PLAYER_SIZE / 2) - (BULLET_SIZE / 2);
            bulletY[j] = py - BULLET_SIZE;
            return;
        }
    }
}

// Redraw the score in the stats bar, but only when it actually changed.
void drawScore(void)
{
    if (score == lastScore) return;
    lastScore = score;
    sprintf(scoreStr, "%05u", score);
    consoleDrawText(7, 1, scoreStr);
}

// Lose SCORE_PER_KILL points (the value an un-hit kill would have earned), clamped at 0.
void penalizeScore(void)
{
    if (score >= SCORE_PER_KILL) score -= SCORE_PER_KILL;
    else                         score = 0;
}

// Redraw the remaining lives in the stats bar, only when it changed.
void drawLives(void)
{
    if (lives == lastLives) return;
    lastLives = lives;
    sprintf(livesStr, "%u", (unsigned short)lives);   // promote: 816-tcc won't widen char varargs
    consoleDrawText(19, 1, livesStr);
}

// Redraw the bomb count in the stats bar, only when it changed.
void drawBombs(void)
{
    if (bombs == lastBombs) return;
    lastBombs = bombs;
    sprintf(bombStr, "%u", (unsigned short)bombs);
    consoleDrawText(27, 1, bombStr);
}

// Intro splash screen: title + a "START GAME" menu item over the drifting
// starfield, with a looping marimba fanfare. Blocks until the player presses
// START, then wipes its text so nothing bleeds into the playfield. Assumes the
// SPC700 is already booted and the starfield/BG layers are up.
void showTitleScreen(void)
{
    unsigned short down0;
    unsigned char step = 0, frame = 0, note;

    // Keep the player sprite out of sight while the splash is up.
    oamSet(OAM_PLAYER, 0, OFFSCREEN_Y, 3, 0, 0, GFX_PLAYER, 0);

    // Title + menu item, roughly centred on the 32-column screen.
    consoleDrawText(11,  9, "MEGA DRIVER");
    consoleDrawText(12, 11, "INVADERS");
    consoleDrawText( 9, 16, "> START GAME <");
    consoleDrawText(10, 20, "PRESS START");

    while (1)
    {
        down0 = padsDown(0);

        // Let the starfield keep drifting under the title.
        starScroll -= STAR_SCROLL_PX;
        bgSetScroll(2, 0, starScroll);

        // Step the fanfare: one note (or rest) every JINGLE_STEP_FRAMES, looping.
        if (frame == 0)
        {
            note = jingleNotes[step];
            if (note) spcEffect(note, SFX_COWBELL, 15 * 16 + PAN_CENTER);
            if (++step >= JINGLE_LEN) step = 0;
        }
        if (++frame >= JINGLE_STEP_FRAMES) frame = 0;

        if (down0 & KEY_START) break;

        spcProcess();
        WaitForVBlank();
    }

    // Wipe the splash text (overwrite each line with matching-length blanks).
    consoleDrawText(11,  9, "           ");
    consoleDrawText(12, 11, "        ");
    consoleDrawText( 9, 16, "              ");
    consoleDrawText(10, 20, "           ");
}

int main(void)
{
    unsigned short pad0, down0;
    unsigned char i, j;
    short x = 112, y = 170;     // player position (starts near the bottom)

    // --- Sound engine: boot the SPC700 and load our effect samples ---
    spcBoot();
    spcSetBank(&SOUNDBANK__);
    // Reserve SPC RAM for BRR sound effects (gunshot is ~12 256-byte blocks);
    // do this before loading any sounds, as in the PVSnesLib likemario sample.
    spcAllocateSoundRegion(16);
    spcStop();
    for (i = 0; i < NUM_SFX; i++) spcLoadEffect(i);
    // Register the gunshot BRR sample (vol 15, centre pan, pitch 4) as sound 0.
    spcSetSoundEntry(15, PAN_CENTER, 4,
                     (u16)(&gunshot_brrend - &gunshot_brr), &gunshot_brr, &gunSound);

    // --- Text console (uses the bundled pvsneslib font) ---
    consoleSetTextMapPtr(0x6800);
    consoleSetTextGfxPtr(0x3000);
    consoleSetTextOffset(0x0100);
    consoleInitText(0, 16 * 2, &tilfont, &palfont);

    bgSetGfxPtr(0, 0x2000);
    bgSetMapPtr(0, 0x6800, SC_32x32);
    setMode(BG_MODE1, 0);
    bgSetDisable(1);

    // Dark blue night sky instead of the default black backdrop.
    setPaletteColor(0, SKY_COLOR);

    // --- Scrolling starfield on BG2 (built once, then only scrolled) ---
    buildStarfield();
    dmaCopyVram(starTiles, STAR_GFX_VRAM, sizeof(starTiles));
    dmaCopyVram((u8 *)starMap, STAR_MAP_VRAM, sizeof(starMap));
    bgSetGfxPtr(2, STAR_GFX_VRAM);
    bgSetMapPtr(2, STAR_MAP_VRAM, SC_32x32);
    setPaletteColor(STAR_PAL * 4 + 1, RGB5(31, 31, 31));   // bright star
    setPaletteColor(STAR_PAL * 4 + 2, RGB5(15, 17, 26));   // dim star
    bgSetEnable(2);

    // --- Stats bar: top 3 rows (y 0..23), kept clear of gameplay ---
    // Row 0 lands in the overscan ZSNES crops, so the HUD sits on row 1 (the
    // topmost fully-visible row).
    consoleDrawText(1, 1, "SCORE");
    consoleDrawText(13, 1, "LIVES");
    consoleDrawText(21, 1, "BOMBS");
    drawScore();
    drawLives();
    drawBombs();

    // --- Player gfx -> VRAM 0x0000, palette slot 0. Sizes: small 8, large 32. ---
    oamInitGfxSet(&sprites_til, (&sprites_tilend - &sprites_til),
                  &sprites_pal, (&sprites_palend - &sprites_pal),
                  0, VRAM_PLAYER, OBJ_SIZE8_L32);

    // --- Enemy + bullet gfx/palettes (loaded while the screen is still off) ---
    dmaCopyVram(&enemy_til,  VRAM_ENEMY,  (&enemy_tilend  - &enemy_til));
    dmaCopyVram(&bullet_til, VRAM_BULLET, (&bullet_tilend - &bullet_til));
    dmaCopyVram(&powerup_til, VRAM_POWERUP, (&powerup_tilend - &powerup_til));
    dmaCopyVram(&tac2_til,   VRAM_TANK,   (&tac2_tilend   - &tac2_til));
    dmaCopyCGram(&enemy_pal,  PAL_ENEMY_CG,  (&enemy_palend  - &enemy_pal));
    dmaCopyCGram(&bullet_pal, PAL_BULLET_CG, (&bullet_palend - &bullet_pal));
    dmaCopyCGram(&powerup_pal, PAL_POWERUP_CG, (&powerup_palend - &powerup_pal));
    dmaCopyCGram(&tac2_pal,   PAL_TANK_CG,   (&tac2_palend   - &tac2_pal));

    // Player: sprite 0, priority 3 (in front), large (32x32), palette 0
    oamSet(OAM_PLAYER, x, y, 3, 0, 0, GFX_PLAYER, 0);
    oamSetEx(OAM_PLAYER, OBJ_LARGE, OBJ_SHOW);

    // Enemies: large (32x32), palette 1. Reserve all MAX_ENEMIES OAM slots (parked
    // off-screen) so the dormant ones stay hidden until the score ramp activates
    // them; only the START_ENEMIES active ones get a starting position.
    for (i = 0; i < MAX_ENEMIES; i++)
    {
        enemyType[i]   = ENEMY_NORMAL;
        enemyHealth[i] = 1;
        enemyHurt[i]   = 0;
        if (i < activeEnemies)
            spawnEnemy(i);                 // sets position + the right gfx/palette
        else
        {
            oamSet(OAM_ENEMY(i), 0, OFFSCREEN_Y, 2, 0, 0, GFX_ENEMY, 1);
            oamSetEx(OAM_ENEMY(i), OBJ_LARGE, OBJ_SHOW);
        }
    }

    // Bullets: small (8x8), palette 2, parked off-screen until fired
    for (j = 0; j < NUM_BULLETS; j++)
    {
        bulletActive[j] = 0;
        oamSet(OAM_BULLET(j), 0, OFFSCREEN_Y, 2, 0, 0, GFX_BULLET, 2);
        oamSetEx(OAM_BULLET(j), OBJ_SMALL, OBJ_SHOW);
    }

    // Bomb power-up: large (32x32), palette 3, parked off-screen until dropped
    oamSet(OAM_POWERUP, 0, OFFSCREEN_Y, 2, 0, 0, GFX_POWERUP, 3);
    oamSetEx(OAM_POWERUP, OBJ_LARGE, OBJ_SHOW);

    setScreenOn();

    // Intro splash: title + "START GAME" menu, with a fanfare. Returns once the
    // player presses START, dropping straight into the action below.
    showTitleScreen();

    while (1)
    {
        pad0  = padsCurrent(0);
        down0 = padsDown(0);

        // --- Starfield: scroll the whole BG2 layer down one notch. Done here,
        //     during the post-VBlank window, so it stays tear-free, and before
        //     the game-over check so the sky keeps drifting while frozen. ---
        starScroll -= STAR_SCROLL_PX;
        bgSetScroll(2, 0, starScroll);

        // Out of lives: freeze the field (sprites hold their last positions)
        // until START is pressed, then wipe state and drop back into the action.
        if (gameOver)
        {
            if (down0 & KEY_START)
            {
                score = 0;            lastScore = 0xFFFF;  // force HUD redraw
                lives = START_LIVES;  lastLives = 0xFF;
                bombs = START_BOMBS;  lastBombs = 0xFF;
                playerFlash = 0;
                powerupActive = 0;
                killsSinceDrop = 0;   dropThreshold = 10;
                x = 112; y = 170;                          // player back at the start
                activeEnemies = START_ENEMIES;             // back to the gentle opening wave
                nextEnemyScore = ENEMIES_PER_LEVEL;        // reset the difficulty ramp
                for (i = 0; i < MAX_ENEMIES; i++)
                {
                    enemyType[i]   = ENEMY_NORMAL;
                    enemyHealth[i] = 1;
                    enemyHurt[i]   = 0;
                    if (i < activeEnemies)
                        spawnEnemy(i);     // fresh active enemies (sets gfx/palette)
                    else
                        oamSet(OAM_ENEMY(i), 0, OFFSCREEN_Y, 2, 0, 0, GFX_ENEMY, 1);  // park the rest
                }
                for (j = 0; j < NUM_BULLETS; j++) bulletActive[j] = 0;
                consoleDrawText(11, 13, "         ");       // erase "GAME OVER"
                consoleDrawText(10, 15, "           ");     // erase "PRESS START"
                gameOver = 0;
            }
            spcProcess();
            WaitForVBlank();
            continue;
        }

        if (pad0 & KEY_LEFT  && x > 0)                 x -= 2;
        if (pad0 & KEY_RIGHT && x < SCREEN_W - PLAYER_SIZE) x += 2;   // 256 - 21
        if (pad0 & KEY_UP    && y > PLAYFIELD_TOP)      y -= 2;       // stay below stats bar
        if (pad0 & KEY_DOWN  && y < 224 - PLAYER_SIZE)  y += 2;       // 224 - 21

        if (down0 & (KEY_A | KEY_B)) { fireBullet(x, y); sfxFire(); }

        // Y = screen-clearing bomb: spend one from inventory to detonate every
        // console at once. Does nothing when the player is out of bombs.
        if ((down0 & KEY_Y) && bombs > 0)
        {
            bombs--;
            for (i = 0; i < activeEnemies; i++) killEnemy(i);   // a bomb flattens even tanks
        }

        // Draw the player; while flashing (recently hit) blink on/off every 4 frames.
        // Per-frame updates use oamSetXY (position only) -- the attributes were set
        // once at init, so there's no need to rewrite them every frame.
        if (playerFlash > 0) playerFlash--;
        if (playerFlash > 0 && ((playerFlash >> 2) & 1))
            oamSetXY(OAM_PLAYER, 0, OFFSCREEN_Y);
        else
            oamSetXY(OAM_PLAYER, x, y);

        // --- Move bullets up; deactivate once they leave the top edge ---
        for (j = 0; j < NUM_BULLETS; j++)
        {
            if (bulletActive[j])
            {
                bulletY[j] -= BULLET_SPEED;
                if (bulletY[j] < PLAYFIELD_TOP) bulletActive[j] = 0;   // stop at the stats bar
            }
        }

        // --- Difficulty ramp: the more the score climbs, the more consoles are in
        //     play at once -- one extra each time the score passes the next
        //     ENEMIES_PER_LEVEL threshold, capped at MAX_ENEMIES. A slow, steady
        //     build, never a sudden swarm. Each newly activated enemy drops in from
        //     the top like a normal spawn. The while handles a bomb that crosses
        //     several thresholds in one frame. ---
        while (activeEnemies < MAX_ENEMIES && score >= nextEnemyScore)
        {
            spawnEnemy(activeEnemies++);
            nextEnemyScore += ENEMIES_PER_LEVEL;
        }

        // --- Update enemies: flashing ones freeze then respawn, others descend ---
        for (i = 0; i < activeEnemies; i++)
        {
            if (enemyHurt[i] > 0) enemyHurt[i]--;         // chipped flicker fades (keeps descending)
            if (enemyFlash[i] > 0)
            {
                enemyFlash[i]--;
                if (enemyFlash[i] == 0) spawnEnemy(i);   // destroyed enemy gone, new one drops in
            }
            else
            {
                // Sub-pixel descent: accumulate 1/256ths, advance whole pixels.
                unsigned short acc = enemyFrac[i] + (unsigned short)enemySpeed[i];
                enemyY[i]   += (short)(acc >> 8);
                enemyFrac[i] = (unsigned char)(acc & 0xFF);
                if (enemyY[i] >= 224)        // escaped un-hit off the bottom
                {
                    penalizeScore();
                    spawnEnemy(i);
                }
            }
        }

        // --- Collisions: bullet (8x8) vs enemy (32x32) ---
        for (j = 0; j < NUM_BULLETS; j++)
        {
            if (!bulletActive[j]) continue;
            for (i = 0; i < activeEnemies; i++)
            {
                if (enemyFlash[i] > 0) continue;          // already hit
                if (bulletX[j] + BULLET_SIZE > enemyX[i] &&
                    bulletX[j] < enemyX[i] + ENEMY_SIZE &&
                    bulletY[j] + BULLET_SIZE > enemyY[i] &&
                    bulletY[j] < enemyY[i] + ENEMY_SIZE)
                {
                    bulletActive[j] = 0;   // bullet spent
                    damageEnemy(i);        // chip a tank, or destroy a console
                    break;
                }
            }
        }

        // --- Collisions: player (21x21) vs enemy. Costs a life + flash; brief i-frames ---
        if (playerFlash == 0)
        {
            for (i = 0; i < activeEnemies; i++)
            {
                if (enemyFlash[i] > 0 || enemyY[i] < PLAYFIELD_TOP) continue;  // not a live target
                if (x + PLAYER_SIZE > enemyX[i] &&
                    x < enemyX[i] + ENEMY_SIZE &&
                    y + PLAYER_SIZE > enemyY[i] &&
                    y < enemyY[i] + ENEMY_SIZE)
                {
                    if (lives > 0) lives--;
                    spawnEnemy(i);                         // the console that hit us is gone (no score)
                    if (lives == 0)
                    {
                        gameOver = 1;
                        consoleDrawText(11, 13, "GAME OVER");
                        consoleDrawText(10, 15, "PRESS START");
                        sfxGameOver();                     // mournful strings
                    }
                    else
                    {
                        playerFlash = PLAYER_FLASH_FRAMES; // blink + invulnerable for a moment
                        sfxCollide();                      // took a hit
                    }
                    break;
                }
            }
        }

        // --- Bomb power-up: fall, get caught by the player, or drop off the bottom ---
        if (powerupActive)
        {
            powerupY += POWERUP_SPEED;
            if (powerupY >= 224)
                powerupActive = 0;                         // missed -- fell off-screen
            else if (x + PLAYER_SIZE > powerupX &&
                     x < powerupX + POWERUP_SIZE &&
                     y + PLAYER_SIZE > powerupY &&
                     y < powerupY + POWERUP_SIZE)
            {
                powerupActive = 0;
                if (bombs < MAX_BOMBS) bombs++;            // collected: stock a bomb
                sfxPowerup();
            }
        }

        // --- Draw enemies ---
        for (i = 0; i < activeEnemies; i++)
        {
            // Hidden while still above the stats bar (keeps the top row clear),
            // on the "off" beat of the death blink, or mid chipped-hit flicker.
            if (enemyY[i] < PLAYFIELD_TOP ||
                (enemyFlash[i] > 0 && ((enemyFlash[i] >> 1) & 1)) ||
                (enemyHurt[i] > 0 && (enemyHurt[i] & 1)))
                oamSetXY(OAM_ENEMY(i), 0, OFFSCREEN_Y);
            else
                oamSetXY(OAM_ENEMY(i), enemyX[i], (unsigned char)enemyY[i]);
        }

        // --- Draw bullets ---
        for (j = 0; j < NUM_BULLETS; j++)
        {
            if (bulletActive[j])
                oamSetXY(OAM_BULLET(j), bulletX[j], (unsigned char)bulletY[j]);
            else
                oamSetXY(OAM_BULLET(j), 0, OFFSCREEN_Y);
        }

        // --- Draw the bomb power-up ---
        if (powerupActive)
            oamSetXY(OAM_POWERUP, powerupX, (unsigned char)powerupY);
        else
            oamSetXY(OAM_POWERUP, 0, OFFSCREEN_Y);

        drawScore();
        drawLives();
        drawBombs();

        spcProcess();        // feed queued sound messages to the SPC700 each frame
        WaitForVBlank();
    }
    return 0;
}
